server:
  port: ${port:56010} #启动端口
spring:
  application:
    name: quickstart-provider
  cloud:
    nacos:
      discovery:
        server-addr: 122.51.74.196:8848
logging:
  level:
    root: info
    org.springframework: info